
version: '3.0'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      LLAMA_MODEL: ${LLAMA_MODEL}
    volumes:
      - ../goinfre:/goinfre
    ports:
      - 1664:3000
  